services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./backend/backend:/backend
    command: python3.12 /backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend/node/frontend:/usr/src/app/frontend
    command: sh -c "cd /usr/src/app/frontend && yarn start"
    ports:
      - "3000:3000"