services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./backend/backend:/backend
    command: python3.12 /backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app  # 修正: frontend全体をマウント
      - /usr/src/app/node_modules # 修正: node_modulesを除外
    command: ["npm", "run", "dev"] # 修正: `npm start` ではなく `npm run dev`
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
